apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderinfo
  labels:
    app: orderinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderinfo
  template:
    metadata:
      labels:
        app: orderinfo
    spec:
      containers:
        - name: orderinfo
          image: username/orderinfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5